gawel/pyquery

- pyquery/pyquery.py
fix `make_links_absolute` when label hasn't such an attr, never add it, and make all links in label `<a>`,`<link>`,<script>,<img> and `<iframe>` absolute
> make_links_absolute when label hasn't such attr, never add it, and make all links in label a,link,script,img and iframe absolute

- pyquery/pyquery.py
Implemented usage `lxml.etree.tostring` within `outer_html` method (similar to `html` method) instead of `lxml.html.tostring` which caused auto-encoding URLs
> implemented usage `lxml.etree.tostring` within `outer_html` method

- pyquery/pyquery.py
- tests/test_pyquery.py
This ensures that the `namespaces` argument passed into `PyQuery()` will also be passed into any internally created copies. That allows you to set `namespaces` a single time rather than over and over.
Example before this pull:
```
namespaces = {'foo':'http://example.com/foo'}
d = pq(xml, parser='xml')
val = d('foo|bar', namespaces=namespaces).closest('foo|baz', namespaces=namespaces).children('foo|boo', namespaces=namespaces)
```
Example after this pull:
```
namespaces = {'foo':'http://example.com/foo'}
d = pq(xml, parser='xml', namespaces=namespaces)
val = d('foo|bar').closest('foo|baz').children('foo|boo')
```
Also added a couple of tests to ensure that namespaces are passed to copies.
> Preserve namespaces attribute on PyQuery copies.

- pyquery/pyquery.py
using `make_links_absolute` to handle the link startswith whitespace, like this:
``` html
-- http://www.target.com/
<html>
<a href="        /hello.php">test</a>
<html>
```
result: 
`http://www.target.com/        /hello.php`
what I expect :
`http://www.target.com/hello.php`
just work like a browser
> make_links_absolute: link startswith whitespace

- CHANGES.rst
- pyquery/pyquery.py
- tests/test_pyquery.py
`val()` implementation always relied on `value` attribute, which works for `<input>` elements, but not for `<textarea>` and `<select>`. Those need special treatment based on `text` and `<option selected>` respectively.
> Fix val() for <textarea> and <select>, to match jQuery behavior

- .gitignore
- .travis.yml
- pyquery/pyquery.py
- pyquery/text.py
- seleniumtests/base.py
- seleniumtests/browser.py
- seleniumtests/offline.py
- setup.cfg
- tox.ini
I'm not sure how to organize tests. They consist of two parts:
- testing selenium output to ensure correctness of TextExtractionMixin
- testing our code with same TextExtractionMixin
I don't know whether Travis supports selenium, so I put my tests separately.
```bash
python -m unittest seleniumtests.offline
python -m unittest seleniumtests.browser
```
Added same lines to tox config, but `browser` test hangs.
You can change selenium driver in `browser.py:71`. Recent Firefox hangs, but Chrome worked for me. Under tox both hang, probably due to lack of some envvars, like current X display.
> text() output compatible with selenium .text property #99

- pyquery/pyquery.py
- tests/test_pyquery.py
As described in #102, calling `element.html(content)` currently deletes any tail text after the element, when it should only replace the contents of the element. This PR fixes that issue, and adds a test to verify that `element.html(content)` works as expected.
Fixes #102
> Preserve tail text when calling html(content)

- pyquery/pyquery.py
- tests/test_pyquery.py
As per the jQuery API, `val()` handles `select` elements with the `multiple` attribute by setting and getting arrays of strings, toggling the selection of multiple `option`s. For non-`select` elements, `val()` concatenates array items.
Additionally, setting the value for non-multiple `select` elements now only activates the first matching `option`, whereas previously all `option`s with the duplicate value would be selected.
Added docs and tests, which have passed.
> val() should handle setting array of strings and select-multiple elements

- pyquery/pyquery.py
I also ran into the issue where `.text()` no longer returned newlines, and after digging through the code and experimenting a bit I found that setting the `squash_space` option to `False` fixed my issue.
This PR quickly documents that option.
This could be considered a "fix" to #181.
> Documentation for #181 - don't squash newlines

- pyquery/pyquery.py
Reproduce the bug with:
```
In [1]: from pyquery import PyQuery as pq
In [2]: html = '<a href="tel:1234">phone us</a>'
In [3]: p = pq(html)
In [4]: p.make_links_absolute('http://example.com')[0].attrib['href']
Out[4]: 'http://example.com/tel:1234'
```
After my patch:
```
In [9]: p.make_links_absolute('http://example.com')[0].attrib['href']
Out[9]: 'tel:1234'
```
(added support of the `tel:`, `sms:` (used by mobile/smartphone OSes) and `callto:` (used by Skype)
I found out about this one while using pyspider, it was keeping yielding weird URLs like `http://example.com/tel:1234` while the `tel:1234` was perfectly alright.
Reference: https://css-tricks.com/the-current-state-of-telephone-links/
It doesn't seem to be in the HTML standard, but is heavily used on various sites that provide …
> Fix make_links_absolute to support tel:, sms:

- pyquery/cssselectpatch.py
- tests/test_pyquery.py
The jQuery library selects [:disabled and :enabled pseudo-classes](https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/external/sizzle/dist/sizzle.js#L467) according to the [WHATWG spec](https://html.spec.whatwg.org/multipage/semantics-other.html#concept-element-disabled).
This PR uses a somewhat convoluted XPath condition to conform to spec. It may presumably be improved upon. Additional tests added pass.
> Follow WHATWG spec when selecting :disabled and :enabled

- pyquery/pyquery.py
- tests/test_pyquery.py
Adds functionality to handle form element serialization. `serialize()` and `serializeArray()` mimic their jQuery counterparts in terms of output. As the `{ name, value }` format is less useful for most Python applications, this PR introduces formats compatible with, e.g., the [Requests](http://docs.python-requests.org/en/master/user/quickstart/#more-complicated-post-requests) library:
* `serializePairs()` => `[('order', 'spam'), ('order', 'eggs'), ('order2', 'ham')]`
* `serializeDict()` => `OrderedDict([('order', ['spam', 'eggs']), ('order2', 'ham')])` 
I have added documentation and passing tests (whose results agree with jQuery 3.3.1).
Note that this includes a minor fix for the `root()` method, and strips newlines when querying the value of non-radio, non-checkbox `input` elements.
> Serialize form elements

- docs/scrap.rst
- pyquery/openers.py
- tests/test_pyquery.py
Added a couple of necessary features for web scraping:
* support for `timeout` parameter with default timeout of 60 seconds (supported for both urllib and requests)
* support for `session` parameter to allow providing a [requests session object](http://docs.python-requests.org/en/master/user/advanced/#session-objects) for persistence between requests (e.g. to keep cookies)
regarding setting a default timeout - see this comment and discussion - https://github.com/requests/requests/issues/3070#issuecomment-318949822
> web scraping improvements: default timeout and session support

- pyquery/pyquery.py
When val is None, you can't do val.replace() because it's not a string.
> Fix error when an input has no value

- CHANGES.rst
- pyquery/pyquery.py
- tests/test_pyquery.py
Currently the `.html()` method does not escape the `tag.text` portion of the response:
```
In [1]: pq('<div>encoded &lt;script&gt; tag</div>').html()
Out[1]: 'encoded <script> tag'
```
This PR updates `.html()` to call the builtin `html.escape()` function on `tag.text`. We can set `quote=False` because we're escaping element text rather than attribute text.
Fixes #205 #218 #200 #178
> Escape entities in html() output

- CHANGES.rst
- pyquery/pyquery.py
- tests/test_pyquery.py
In PyQuery, `remove()` currently adds a space in place of the removed element:
```
>>> print(PyQuery('<a>1<b>2</b>3</a>').remove('b'))
<a>1 3</a>
```
The same line in jQuery would print `<a>12</a>`.
I think jQuery's behavior is correct here, because the new space will sometimes change the semantics of the document. And it's possible to manually add a space after the target element before removing it, if you want a space, but not possible to manually remove the space if you don't want it.
So, this PR removes the extra space from `remove()`.
> remove() no longer adds a space

- CHANGES.rst
- docs/scrap.rst
- pyquery/pyquery.py
- tests/test_pyquery.py
As discussed in #203, this updates PyQuery to only treat inputs as URLs if they are explicitly labeled, like `PyQuery(url="http://example.com")`.
Fixes #203
> Require url inputs to be explicit

- README.rst
update and fix simple typo and sentence
> update and fix simple typo and sentence

- docs/pseudo_classes.rst
- pyquery/cssselectpatch.py
- pyquery/pyquery.py
- pyquery/text.py
There are small typos in:
- docs/pseudo_classes.rst
- pyquery/cssselectpatch.py
- pyquery/pyquery.py
- pyquery/text.py
Fixes:
- Should read `elements` rather than `elelements`.
- Should read `artificially` rather than `artifically`.
- Should read `another` rather than `anoter`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- .github/workflows/tox.yml
- tox.ini
https://docs.python.org/3.11/whatsnew/3.11.html
> Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite.
> GitHub Actions: Add Python 3.11 to the testing
